<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0b0e0162a3e25f993d763491aadc2546
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AmirSasani\\RealtynaTest\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AmirSasani\\RealtynaTest\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0b0e0162a3e25f993d763491aadc2546::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0b0e0162a3e25f993d763491aadc2546::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0b0e0162a3e25f993d763491aadc2546::$classMap;

        }, null, ClassLoader::class);
    }
}
